### ISSUE TITLE
InvalidOperationException when trying to update Genshin Impact

### ISSUE THREAD

**Issue by Xpl0itR** [neon-nyan/CollapseLauncher#16]
The registry value of `selectedServerName` is null, but gets casted to an int which throws.
https://github.com/neon-nyan/CollapseLauncher/blob/main/Hi3HelperCore/Classes/Preset/Classes/PresetConfigClasses.cs#L141

For context, I reinstalled windows since installing genshin and haven't played it since before so some registry keys don't exist

**Comment by neon-nyan** [comment]
Hi there,

Thank you for reporting this issue.
Seems like the throw comes from ``value`` while at the same time it:s trying to set the first value of the keys which doesn't exist, or doesn't it?

I will try to look into this later.

**Comment by Xpl0itR** [comment]
I checked the registry and the `GENERAL_DATA` key did exist, but the JSON data inside were all default values. `selectedServerName` was "". I changed that to "2" and then the launcher didn't crash when clicking the update button.

**Comment by neon-nyan** [comment]
**Hi there,**

This issue should've been addressed in [**this commit.**](https://github.com/neon-nyan/CollapseLauncher/commit/328628d45f96d317e7fbdf047abdbf0e2db7b13c)

You can check that out and if there's another thing went wrong with it, please leave a comment here.

**Comment by Xpl0itR** [comment]
LGTM, thanks
