### ISSUE TITLE
[BUG] Launcher freezing

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#19]
When downloading a new update or the game the launcher will freeze for some reason
![image_2022-09-15_102144053](https://user-images.githubusercontent.com/12277635/190353417-47e66a47-7030-4a08-9c14-eda182be142d.png)
and if you try to force close the launcher and then reopen it the launcher will constantly fail to actually locate the installed game. It happened with Honkai Impact 3rd Global, I don't know if it can happen with other game versions, although it's highly likely it can. By the way, in the Task Manager it shows an usage of around 10MB/s while being in that state, and the download actually continues, it just the launcher that freezes

**Comment by muscularcandy67** [comment]
On a further analysis, seems like the issue is based on the network speed. What I guess happens is that with high speed internet the progress bar updates more frequently, therefore when it's time to redraw the bar it already needs an update, and goes into a loop that results in the launcher UI freezing. My reason? I limited my speed to 4-5MB/s and yes it's taking longer, but no freezes. I will update this comment if it ends up freezing at some point with this speed

**Comment by KorewaLidesu** [comment]
> On a further analysis, seems like the issue is based on the network speed. What I guess happens is that with high speed internet the progress bar updates more frequently, therefore when it's time to redraw the bar it already needs an update, and goes into a loop that results in the launcher UI freezing. My reason? I limited my speed to 4-5MB/s and yes it's taking longer, but no freezes. I will update this comment if it ends up freezing at some point with this speed

I'm getting 7MB/s on download but no freezing issue.

**Comment by muscularcandy67** [comment]
Installing it on an SSD, and I'm sure something happens when on high speed above 7MB/s, not sure at which point starts to freeze, but it happened also while predownloading

**Comment by muscularcandy67** [comment]
@neon-nyan don't worry about it, everyone has life, plus this is just a personal project for you that you are sharing with us. I'm tho saddened that I encountered two bugs (altho one was really just a small issue) and I was the only one to report them

**Comment by muscularcandy67** [comment]
Okay I actually already compiled the update yesterday before you released it, and I did a test installation on Honkai Impact 3rd SEA and the launcher didn't freeze

**Comment by neon-nyan** [comment]
Good to hear that. I think we can close this issue for now.
