### ISSUE TITLE
[BUG] Issue with config.ini and update bug

### ISSUE THREAD

**Issue by KorewaLidesu** [neon-nyan/CollapseLauncher#20]
### Newly install or upgrade will give wrong `config.ini`.

> P/s: For first time after install, the launcher will working correctly even with wrong `config.ini`. But after *restart* it, the launcher won't work as expected. 

- Normal `config.ini` (This is a backup file from old version):

```
[launcher]
channel=1
cps=
game_version=5.8.0
sub_channel=1
sdk_version=
game_install_path=D:\GAME\CollapseFolder\Hi3SEA
game_start_name=BH3.exe
is_first_exit=False
exit_type=2

```

- Wrong `config.ini` (Can be obtain by newly install or update game via normal path or delta patch):
```
[General]
channel=1
cps=
game_version=6.0.0
sub_channel=1
sdk_version=
```

### Update issue:
I get this issue after apply the *fix* config.ini, in this case is above one.
When start launcher, it recognizes the game but requires me to update the game once again.
Do the update and the first issue (above one) happens

**Comment by KorewaLidesu** [comment]
Exception Throw:
```
System.Exception: The Game Profile config.ini seems to be messed up. Please check your Game Profile "config.ini" located in this folder:
D:\GAME\CollapseFolder\Hi3SEA\config.ini
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Hi3Helper.Data.ConverterTool.NormalizePath(String i) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Data\Tools\ConverterTool.cs:line 44
   at Hi3Helper.Shared.Region.InstallationManagement.LoadGameConfig() in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Shared\Region\InstallationManagement.cs:line 40
   --- End of inner exception stack trace ---
   at Hi3Helper.Shared.Region.InstallationManagement.LoadGameConfig() in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Shared\Region\InstallationManagement.cs:line 51
   at CollapseLauncher.Pages.HomePage..ctor() in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 50
```

**Comment by neon-nyan** [comment]
Hi there,

While looking into the config.ini above, I noticed that the "before" one got mixed with the config.ini from both launcher and game scope before the update. That's why after the game got updated, some parameters from launcher scope like: ``game_install_path``, ``game_start_name``, etc were missing.

Keep in mind that both Official Launcher and Collapse Launcher is using the same mechanism, which is using two different config.ini for game installation handling. The first one is for **``launcher scope``** (which is handling where the game should be located) and the second is for **``game scope``** (which is only handling the version and update channel of the game itself).

This is an example of config.ini for launcher scope:
```
[launcher]
cps=
channel=1
sub_channel=1
game_install_path=C:/Program Files/Honkai Impact 3 sea/Games
game_start_name=BH3.exe
is_first_exit=False
exit_type=2
```

and here's for game scope:
```
[General]
channel=1
cps=
game_version=6.0.0
sub_channel=1
sdk_version=
```

You can try remove every **``launcher scope``** sections inside of the config.ini and try relocate the installation by pressing Install Game button > Locate Directory > Choose a folder where the BH3.exe and config.ini file is located. Then, the launcher will automatically register the game installation once again.

**Comment by KorewaLidesu** [comment]
>You can try remove every launcher scope sections inside of the config.ini and try relocate the installation by pressing Install Game button > Locate Directory > Choose a folder where the BH3.exe and config.ini file is located. Then, the launcher will automatically register the game installation once again.

This does indeed work, but after it requires me to update the game.

**Comment by neon-nyan** [comment]
Did you already installed the update before? Also make sure if there's ``BH3.exe`` executable file there.

If yes, maybe you can try changing the ``game_version`` in Game's ``config.ini`` then try again

**Comment by KorewaLidesu** [comment]
> Did you already installed the update before? Also make sure if there's `BH3.exe` executable file there.
> 
> If yes, maybe you can try changing the `game_version` in Game's `config.ini` then try again

No, it is newly installation. I have tried it after update cause previous issue.

**Comment by KorewaLidesu** [comment]
![image](https://user-images.githubusercontent.com/24401452/191898295-46776939-b171-4828-af6a-864e28eb0be3.png)
```
[launcher]
cps=
channel=1
sub_channel=1
game_install_path=D:/GAME/CollapseFolder/Hi3SEA
game_start_name=BH3.exe
is_first_exit=False
exit_type=2
```

**Comment by neon-nyan** [comment]
> ```
> [launcher]
> cps=
> channel=1
> sub_channel=1
> game_install_path=D:/GAME/CollapseFolder/Hi3SEA
> game_start_name=BH3.exe
> is_first_exit=False
> exit_type=2
> ```

Are these section actually the content of the config.ini file in your screenshot? Just to make sure.

**Comment by KorewaLidesu** [comment]
> Are these sections actually the content of the `config.ini` file in your screenshot? Just to make sure.

Yes it is

**Comment by neon-nyan** [comment]
Ah, that's the reason why.
The one you have was the Launcher scope. Instead, you should have Game scope, which is this one:

```
[General]
channel=1
cps=
game_version=6.0.0
sub_channel=1
sdk_version=
```

Can you try replace those sections with this?

**Comment by KorewaLidesu** [comment]
- After replacement:
```
System.Exception: The Game Profile config.ini seems to be messed up. Please check your Game Profile "config.ini" located in this folder:
D:\GAME\CollapseFolder\Hi3SEA\config.ini
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Hi3Helper.Data.ConverterTool.NormalizePath(String i) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Data\Tools\ConverterTool.cs:line 44
   at Hi3Helper.Shared.Region.InstallationManagement.LoadGameConfig() in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Shared\Region\InstallationManagement.cs:line 40
   --- End of inner exception stack trace ---
   at Hi3Helper.Shared.Region.InstallationManagement.LoadGameConfig() in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore\Classes\Shared\Region\InstallationManagement.cs:line 51
   at CollapseLauncher.Pages.HomePage..ctor() in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 50
```

**Comment by neon-nyan** [comment]
Hi there,

Just give you an update.
Seems like I'm being able to reproduce your issue.

![image](https://user-images.githubusercontent.com/30566970/192125033-f97649a1-b1d8-4eb3-a768-e0d1d6eb5eae.png)

The issue occurred while the ``game_install_path`` in Launcher Scope's ``config.ini`` is empty.

![image](https://user-images.githubusercontent.com/30566970/192125148-dd16e819-b65e-4b3b-96b3-7ab7aad7485b.png)

I will make a mechanism to relocate your game if the config is missing in the next version.

So, here's a plan for you.
1. Make a new folder named ``Games`` in ``D:\GAME\CollapseLauncher\Hi3SEA`` path.
2. Move all the files in this ``D:\GAME\CollapseLauncher\Hi3SEA`` path to a new created ``D:\GAME\CollapseLauncher\Hi3SEA\Games`` folder.
3. Make a new ``config.ini`` file in this ``D:\GAME\CollapseLauncher\Hi3SEA`` path.
4. Write all the section for ``config.ini`` file in this ``D:\GAME\CollapseLauncher\Hi3SEA`` path with this one:
```
[launcher]
cps=
channel=1
sub_channel=1
game_install_path=D:/GAME/CollapseFolder/Hi3SEA/Games
game_start_name=BH3.exe
is_first_exit=False
exit_type=2

```

**Comment by KorewaLidesu** [comment]
Thanks. Seem like working correctly now. I will check out if there is anything else to do.
*Closed as issue resolve*
