### ISSUE TITLE
[BUG] Game Repair issue

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#25]
On version 1.0.40.9, this error pops up whenever trying to open the Honkai Impact 3rd Game Repair section on every region

![image](https://user-images.githubusercontent.com/12277635/192303433-2e9f6072-c3e7-41f0-82fe-44305671a884.png)
[error.txt](https://github.com/neon-nyan/CollapseLauncher/files/9647137/error.txt)

**Comment by neon-nyan** [comment]
Seems I can't reproduce the issue with the latest preview build (1.0.40.9)
Have you tried reinstalling the launcher before?

https://user-images.githubusercontent.com/30566970/192316251-41e454bd-0986-48fb-82e7-26777f25a235.mp4

**Comment by muscularcandy67** [comment]
I think I my launcher had some weird sheninegans because I updated it through the installer provided on the release page and the launcher showed it was on 1.0.40.9, but now that I'm reopening the launcher after a PC reboot it said I had an update and I was on 1.0.40.5. I think what happened is that the update somewhat failed midway and it was on both 1.0.40.5 and 1.0.40.9 and of course it didn't like it. Now after the update through the launcher itself the game repair page shows up as expected
