### ISSUE TITLE
Issue with Genshin Impact pre-download

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#26]
I'm on the latest preview version 1.0.40.9 and as soon as the launcher should be done with downloading the launcher close itself and on reopening it says I have to resume preloading

https://youtu.be/tm08FxxSmjU

**Comment by neon-nyan** [comment]
Does the partial files (started with .00#) still exist while the download start over?
Just to make sure if it's related with issues on ``Hi3Helper.Http`` submodule or not.

**Comment by neon-nyan** [comment]
I'm trying to follow the process but seems I still can't reproduce the issue. Do you get an error/exception trace from the log?

**Comment by muscularcandy67** [comment]
From a quick look on the logs nothing seems out of place

**Comment by neon-nyan** [comment]
Hi @muscularcandy67,

Just to give you an update. Since this is Hi3Helper.Http submodule issue, I'm currently refactoring the entire code of it.
I'm expecting it to be completed in the next 2 days or sooner.

**Comment by muscularcandy67** [comment]
Only way to find out is to either start a new download or wait for the next Genshin pre-download

**Comment by muscularcandy67** [comment]
Closing this issue since on the 3.2 predownload package I didn't got any error, therefore I can say the issue is resolved
