### ISSUE TITLE
Unhandled exception error when trying to update cache using launcher

### ISSUE THREAD

**Issue by aliimran04** [neon-nyan/CollapseLauncher#27]
I us ethe latest preview version and when I try to update cache it gives unhandled exception error
[error.txt](https://github.com/neon-nyan/CollapseLauncher/files/9657052/error.txt)

**Comment by neon-nyan** [comment]
Hi,
I just noticed that the Hi3Mirror API went crashed causing the update cache to be unusable.
I've just bring the service back. Can you try again?

**Comment by aliimran04** [comment]
I just try again to update the cache and it is working now .

**Comment by neon-nyan** [comment]
I think, we can close this issue since the problem has been fixed
