### ISSUE TITLE
Unable to Change launcher from Honkai to Genshin

### ISSUE THREAD

**Issue by OOPMan** [neon-nyan/CollapseLauncher#29]
First off, thanks for this nice piece of software.

I seem to be unable to switch the launcher between Genshin and Honkai modes. My installation steps where as follows:

1. Install Collapse 1.0.40.9 Preview
2. Start Collapse
3. Select Honkai as game
4. Select existing Honkai Impact folder
5. Install
6. Yes to Migrate the game
7. Launch Honkai, it works, yay!
8. Exit Honkai back to Launcher
9. Click the game drop-down and select Genshin
10. Click the region and select Global
11. Change button visibly becomes active but does not respond to clicks :-(
12. Sadness

**Comment by neon-nyan** [comment]
Hi there,

Does the launcher crashed after clicks or it just stay and become unresponsive?

**Comment by OOPMan** [comment]
@neon-nyan Mostly it just completely ignores the clicks on the Change button and stays responsive to input.

I think once it seemed to just close completely after becoming unresponsive but I don't think an error pop-up appeared. Is there a log file I can send?

**Comment by neon-nyan** [comment]
I see.

Yes, there are two logs you can send. The first one is inside this folder:
```%appdata%\..\LocalLow\CollapseLauncher\```

Second, in this folder:
```%appdata%\..\LocalLow\CollapseLauncher\GameFolder\_logs```

**Comment by OOPMan** [comment]
@neon-nyan Okay, so I don't see any log files at all in the first path, but I have attached from from the second path:

[log-2022-09-27.log](https://github.com/neon-nyan/CollapseLauncher/files/9676025/log-2022-09-27.log)
[log-2022-09-28.log](https://github.com/neon-nyan/CollapseLauncher/files/9676026/log-2022-09-28.log)
[log-2022-09-29.log](https://github.com/neon-nyan/CollapseLauncher/files/9676027/log-2022-09-29.log)

**Comment by OOPMan** [comment]
@neon-nyan I've also attached my `config.ini` (Renamed to `config.ini.txt`) to allow it to be uploaded:

[config.ini.txt](https://github.com/neon-nyan/CollapseLauncher/files/9676034/config.ini.txt)

**Comment by neon-nyan** [comment]
Sorry for my very late response (since I was busy recently).
Yes, I don't see any errors logged into the log file. But I will try to check it further by using the same form of config.ini you attached above.

I will give you an update later.

**Comment by neon-nyan** [comment]
After looking into your config.ini file, seems like that you've located the launcher's ``GameFolder`` in the same location as the game installed. Can you try move the ``GameFolder`` path to another location then try again?

**Comment by OOPMan** [comment]
@neon-nyan Hmmmm, I think I must have misunderstood the purpose of that variable. What kind of path should I set it to? Just a new folder somewhere?

**Comment by OOPMan** [comment]
@neon-nyan Okay, so I delete the `config.ini` and start Collapse. This time I used it's default suggestion of folder but I still don't seem to be able to add Genshin. I'm going to try reset it again and select Genshin as the initial game as see if I can add HI3

**Comment by OOPMan** [comment]
No luck unfortunately. I updated to the new version of the application as well but it doesn't seem to help.

**Comment by OOPMan** [comment]
@neon-nyan I'll keep my eyes out for it, thanks

**Comment by neon-nyan** [comment]
Hi,
I just uploaded the test build for this issue.
Please reproduce the issue by using this build and send me the log once again.

https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.50.2-test

**Comment by OOPMan** [comment]
@neon-nyan Hmmmm, when I tried to download it the file was deleted claiming it has a virus :-/

**Comment by OOPMan** [comment]
![image](https://user-images.githubusercontent.com/248980/193874203-8ed404fc-e4b1-4fdd-9a8e-152cb24c67d2.png)

**Comment by neon-nyan** [comment]
Oh, yep. It happened to me too.
Turns out Windows Defender false detected the ``CollapseLauncher.Hi3CacheUpdater.cmd`` and ``Misc/InstallMediaPack.cmd`` scripts as viruses lol. I will send you the installer instead.

**Comment by neon-nyan** [comment]
I just uploaded the new build and this time as an installer.
Please use that one instead.

**Comment by OOPMan** [comment]
@neon-nyan Thanks, that worked. I'm going to wipe the GameFolder and start from scratch. Will post the logs once I'm done

**Comment by OOPMan** [comment]
@neon-nyan Okay, so there's good news and there's bad news.

The bad news is that the logs don't contain anything :-/

The good news is that I found a way to make it work. It seems that if I click the region checkbox and select a region then hit the Tab key and press Space the launcher pops up a dialog asking if I want to change regions. I click yes and it switches to the other game :-)

It seems like this is maybe some kind of issue with the button accepting focus from the mouse, although since my only desktop development experience is with Qt and C++ that's just a guess, since I know your application uses .NET

**Comment by neon-nyan** [comment]
Okay, I figured out that the button doesn't receive a focus/input blocked by the Invisible Drag Area and It's a known issue with the WinUI 3 Scaling. Somehow the Drag Area got scaled incorrectly (AFAIK) and appear above the region selector/button. So it doesn't respond to the input.
But to make sure, While you can't click on it, can you drag the window on the button? If yes, that might be the cause.

Also, what Windows version and build do you use?

**Comment by OOPMan** [comment]
@neon-nyan I can indeed drag the window using the Change button :-)

I'm on Windows 10 21H2

**Comment by neon-nyan** [comment]
@OOPMan Got it!
I will try to reproduce the issue using the same Windows build and because WinUI 3 1.2-preview2 just came out couple of hours ago before this comment, I will try diagnose this problem using that preview version of WinUI and see if it will be able to fix.

**Comment by OOPMan** [comment]
@neon-nyan Hey there. The latest release that came via the self-update has corrected the input focus issue, although I can no longer easily drag the window around.

This isn't a huge issue though, as I can drag it by other methods.

**Comment by neon-nyan** [comment]
@OOPMan Yep, I'm aware of that. The build on self-update was 1.0.51.1 (IIRC) and it has a bug with title bar drag mechanism.
I just pushed the new 1.0.51.2 build and it should be available in 15 mins after this comment.

If you want to try it immediately, you can just use a build in the link above.
