### ISSUE TITLE
[Request] Support for Custom Launch Argument on Genshin

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#35]
Can you add just a command line argument pass for Genshin, like you did for Honkai? I want to try some arguments and see what works and whatnot, and eventually you can come up with just a setting toggle when everything is tested out. 
You can actually do it on a test branch as to not mess up with the current one

**Comment by neon-nyan** [comment]
That's a good idea. I think we can try to add that in the next Release Candidate 3 release since I'll be focusing on fixes for Release Candidate 2.
I will consider this feature later.

**Comment by muscularcandy67** [comment]
More like you can try, I just had the idea

**Comment by neon-nyan** [comment]
**Hi there,**

I just finished to implement this feature and yes, it's possible to get done so we can test the feature now.
Also, this feature will be included in the next Release Candidate 2

![image](https://user-images.githubusercontent.com/30566970/196533996-fbd0adf5-3d97-415f-8d31-e2563cfb2bfc.png)

### Build download:
https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.52.1-fix20221019-test

**Comment by muscularcandy67** [comment]
All right I'll test it in about an hour and log what works and whatnot (though having a possible list of accepted command line arguments would be great to have). 
P.S. is that Zeenless Zone Zero I see in the background?

**Comment by neon-nyan** [comment]
> P.S. is that Zeenless Zone Zero I see in the background?

Yes, that's Zenless Zone Zero 👀 
> *It's just a custom background btw*

**Comment by muscularcandy67** [comment]
I can say that the argument pass is working, now next step is to find which arguments are accepted and eventually have some being toogleable for user friendliness though that's not necessary

**Comment by muscularcandy67** [comment]
Closing this issue since the support has been added
