### ISSUE TITLE
[Visual Issue] [Genshin Impact] Start Game Button 

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#41]
Start Game button still visible under Pause/Cancel when doing Repair Game on Genshin Impact

https://user-images.githubusercontent.com/12277635/198160791-545f680e-9d4f-4b8f-ab3d-787e0d38c957.mp4

**Comment by neon-nyan** [comment]
This issue should've been fixed in the latest 1.0.52.6 build.

**Comment by muscularcandy67** [comment]
I can confirm the issue is now resolved
