### ISSUE TITLE
[Error] [Honkai Impact 3rd] Unhandled Error

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#42]
Right after updating the game through Collapse Launcher and going to Cache Update
![image](https://user-images.githubusercontent.com/12277635/198223135-d3326698-d82b-4881-93cd-7e746a968aee.png)
Edit: I'm on commit d48a079b8daf38fde2d8a47d8af7fc56a9710ea3

**Comment by MrBMT** [comment]
When going to the mediafire link directly for the delta patch recipes it's just giving a blank page, so I'm wondering if the download links are simply dead.

**Comment by neon-nyan** [comment]
> Right after updating the game through Collapse Launcher and going to Cache Update ![image](https://user-images.githubusercontent.com/12277635/198223135-d3326698-d82b-4881-93cd-7e746a968aee.png) Edit: I'm on commit [d48a079](https://github.com/neon-nyan/CollapseLauncher/commit/d48a079b8daf38fde2d8a47d8af7fc56a9710ea3)

This issue was related to Hi3Mirror and I could confirm that we have some problem while replicating the file from miHoYo server because of the changes of the data structure for the index file. This issue for Global version should be fixed now. Can you try it once again?

**Comment by neon-nyan** [comment]
> When going to the mediafire link directly for the delta patch recipes it's just giving a blank page, so I'm wondering if the download links are simply dead.

For that issue, please check the link once again.
I've just replaced the link with the correct one.

**Comment by muscularcandy67** [comment]
> > Right after updating the game through Collapse Launcher and going to Cache Update ![image](https://user-images.githubusercontent.com/12277635/198223135-d3326698-d82b-4881-93cd-7e746a968aee.png) Edit: I'm on commit [d48a079](https://github.com/neon-nyan/CollapseLauncher/commit/d48a079b8daf38fde2d8a47d8af7fc56a9710ea3)
> 
> This issue was related to Hi3Mirror and I could confirm that we have some problem while replicating the file from miHoYo server due to changes of the data structure for the index file. This issue for Global version should be fixed now. Can you try it once again?

I can confirm the issue is now resolved
