### ISSUE TITLE
Issue with... what?

### ISSUE THREAD

**Issue by xWestLC** [neon-nyan/CollapseLauncher#56]
I'm on Windows 11, using the latest update, and this was the error I've got today (this issue wasn't a thing yesterday, I mean I used the latest -stable- version yesterday without any issues)

https://hastebin.com/eyalekojal.apache

May this be related with the recent Turkish language addition to Genshin? I think it affected the launch page of the original launcher, so idk-

![image](https://user-images.githubusercontent.com/84091547/205623408-e3a2453f-144e-4884-bf3b-52f1f2139dad.png)

**Comment by xWestLC** [comment]
Wait, it got fixed .,.

**Comment by neon-nyan** [comment]
Ah, well.
Anyway, I've already made a fix for this and will be applied for the next minor update (in case the same thing still happen) and FYI that this issue isn't related with the recent language addition to official launcher.

Thank you for reporting this though 👍
